# Generated by Django 4.2.16 on 2024-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_canvas_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvas',
            old_name='time_limite',
            new_name='time_to_wait',
        ),
    ]
