# Generated by Django 4.2.16 on 2024-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_time_limite_canvas_time_to_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='content',
            field=models.TextField(default=models.PositiveIntegerField(default=100)),
        ),
    ]
