# Generated by Django 4.2.16 on 2024-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_canvas_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='content',
            field=models.TextField(),
        ),
    ]
