# Generated by Django 5.1.2 on 2024-11-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_canvas_content_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='time_placed',
            field=models.DateTimeField(),
        ),
    ]
