# Generated by Django 5.1.2 on 2024-11-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_contribution_canvas_alter_contribution_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='time_to_wait',
            field=models.PositiveIntegerField(default=3, verbose_name='Time to wait (in seconds)'),
        ),
    ]
