# Generated by Django 5.1.2 on 2024-11-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_canvas_time_to_wait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='height',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='time_to_wait',
            field=models.PositiveIntegerField(default=10, verbose_name='Time to wait (in seconds)'),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='width',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
