# Generated by Django 4.2.16 on 2024-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_canvasstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasstatistics',
            name='contributions_user',
            field=models.JSONField(default=dict),
        ),
    ]
